server:
  port: 4399
spring:
  application:
    name: film
  datasource:
    url: jdbc:mysql://localhost:3306/moviemanager #???? ???serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis-plus??
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      update-strategy: not_null # ????
      id-type: auto  # ????